### ISSUE TITLE
Adding a LICENSE file

### ISSUE THREAD

**Issue by axdiamond** [iamvickyav/ReceiveDataInAndroid#1]
Hi! I really like this repo, it was very helpful! I wanted to use it as a starter for my app, but you don't have proper license set up. 

Its quite easy to do, and GitHub has a nice guide, here;

https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository

**Comment by iamvickyav** [comment]
Hi, Thanks for your interest. I was not aware of setting up license before. Learned it today, thanks to you. 

I have added the license now. Feel free to use this code
